### ISSUE TITLE
Rebuild fails on Node v0.12.2

### ISSUE THREAD

**Issue by putrinolab1** [floored/node-oculus#3]
Unfortunately, attempting to run "npm install node-oculus" fails with the version of Node (v0.12.2) that we are running. Previously, on 0.10.28, everything builds quite nicely and without any fatal errors. Other than rolling back the Node version, what might be a work around to get back up and running? Curious to also know where failure originated as our efforts to track down cause have not been successful. Any help on this would be GREATLY appreciated.

**Comment by bleveque** [comment]
Hi @putrinolab1 -- would you mind posting the errors you get when running ```npm install node-oculus```? We haven't tested the package on more recent versions of node than 0.10.28, but we can take a look!

**Comment by putrinolab1** [comment]
Sure thing... Starting at where it gets good.

```
6884 verbose linkBins node-oculus@1.0.1
6885 verbose linkMans node-oculus@1.0.1
6886 verbose rebuildBundles node-oculus@1.0.1
6887 verbose rebuildBundles [ '.bin', 'node-gyp' ]
6888 info install node-oculus@1.0.1
6889 verbose unsafe-perm in lifecycle true
6890 info node-oculus@1.0.1 Failed to exec install script
6891 verbose unlock done using /Users/putrinolab/.npm/_locks/node-oculus-3aa69807cb429bd9.lock for /Users/putrinolab/oculus-project/node_modules/node-oculus
6892 verbose stack Error: node-oculus@1.0.1 install: `node-gyp rebuild`
6892 verbose stack Exit status 1
6892 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
6892 verbose stack     at EventEmitter.emit (events.js:110:17)
6892 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
6892 verbose stack     at ChildProcess.emit (events.js:110:17)
6892 verbose stack     at maybeClose (child_process.js:1015:16)
6892 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
6893 verbose pkgid node-oculus@1.0.1
6894 verbose cwd /Users/putrinolab/oculus-project
6895 error Darwin 14.0.0
6896 error argv "node" "/usr/local/bin/npm" "install" "node-oculus"
6897 error node v0.12.2
6898 error npm  v2.7.4
6899 error code ELIFECYCLE
6900 error node-oculus@1.0.1 install: `node-gyp rebuild`
6900 error Exit status 1
6901 error Failed at the node-oculus@1.0.1 install script 'node-gyp rebuild'.
6901 error This is most likely a problem with the node-oculus package,
6901 error not with npm itself.
6901 error Tell the author that this fails on your system:
6901 error     node-gyp rebuild
6901 error You can get their info via:
6901 error     npm owner ls node-oculus
6901 error There is likely additional logging output above.
6902 verbose exit [ 1, true ]
6903 verbose unbuild node_modules/node-oculus
6904 info preuninstall node-oculus@1.0.1
6905 info uninstall node-oculus@1.0.1
6906 verbose unbuild rmStuff node-oculus@1.0.1 from /Users/putrinolab/oculus-project/node_modules
6907 info postuninstall node-oculus@1.0.1
6908 silly gentlyRm /Users/putrinolab/oculus-project/node_modules/node-oculus is being purged from base /Users/putrinolab/oculus-project
6909 verbose gentlyRm don't care about contents; nuking /Users/putrinolab/oculus-project/node_modules/node-oculus
6910 silly vacuum-fs purging /Users/putrinolab/oculus-project/node_modules/node-oculus
6911 silly vacuum-fs quitting because other entries in /Users/putrinolab/oculus-project/node_modules
```

**Comment by bleveque** [comment]
Thanks! It looks like some changes in v8 may be the main issue. E.g.,
```
../v8Macros.h:9:64: error: 'Arguments' in namespace 'v8' does not name a type
 #define JS_FUNCTION(name) v8::Handle<v8::Value> name(const v8::Arguments& args)
```
At some point, we may switch to using something like [nan](https://github.com/iojs/nan) for cross-version compatibility, but for the moment, only v0.10.28 is tested and supported. I will post here if we do update, however we don't have a fixed ETA. If you are interested in a quicker fix, please feel free to fork the repo and submit a PR with updates for greater version support!

Thanks for bringing this to our attention!
