### ISSUE TITLE
Install failing at 'node-gyp rebuild'

### ISSUE THREAD

**Issue by captDaylight** [floored/node-oculus#5]
Anybody else getting this error? Have any thoughts on why I'm getting it?

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/paulchristophe/.nvm/versions/node/v4.1.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "/Users/paulchristophe/.nvm/versions/node/v4.1.1/bin/node" "/Users/paulchristophe/.nvm/versions/node/v4.1.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/paulchristophe/projects/drone-oculus/node_modules/node-oculus
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.3.0
npm ERR! argv "/Users/paulchristophe/.nvm/versions/node/v4.1.1/bin/node" "/Users/paulchristophe/.nvm/versions/node/v4.1.1/bin/npm" "i" "-S" "node-oculus"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! node-oculus@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-oculus@1.0.1 install script 'node-gyp rebuild'.

**Comment by bleveque** [comment]
Hi @captDaylight, this may be a similar issue to [this](https://github.com/floored/node-oculus/issues/3), since we haven't tested on node after v0.10.28 (looks like you have v4.1.1). If you are interested in contributing to support more recent versions of node, we would welcome a pull request!
